export interface Property {
  id: number;
  system_id: number;
  building_id: number;
  portfolio_id: number;
  type: string;
  entity_type: string;
  marketing_name: string;
  name: string;
  address: string;
  address2: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  neighborhood: string;
  syndicate: boolean;
  is_published_for_sale: boolean;
  is_published_for_rent: boolean;
  is_featured_for_rent: boolean;
  is_featured_for_sale: boolean;
  is_for_sale: boolean;
  for_sale_status: string;
  lattitude: number;
  longitude: number;
  media_folder_id: number | null;
  no_bedrooms: number;
  no_bathrooms: number;
  no_floors: number;
  total_area: number;
  area_units: string;
  year_built: string | null;
  open_mon: string;
  open_tues: string;
  open_wed: string;
  open_thurs: string;
  open_fri: string;
  open_sat: string;
  open_sun: string;
  embedded_html_code: string;
  pets_allowed: boolean;
  cat_allowed: boolean;
  dog_allowed: boolean;
  other_allowed: boolean;
  smoking_allowed: boolean;
  posting_title: string;
  primary_leasing_agent_id: number | null;
  primary_sales_contact_id: number | null;
  lease_terms: number;
  lease_terms_units: string;
  target_rent: number;
  target_rent_units: string;
  target_deposit: string;
  sale_price: number;
  sale_terms: string;
  mls_number: string;
  other_tenant_charges: string;
  specials: string;
  available_date: string;
  short_description: string;
  description: string;
  directions: string;
  property_type: string;
  banner_status: string | null;
  promotional_banner_status: string | null;
  banner_status_type: string | null;
  website_id: number;
  schedule_tour_link: string;
  leaseTerms: string[];
  images: {
    id: number;
    system_id: number;
    order_index: number;
    original_image_url: string;
    small_image_url: string;
    thumb_image_url: string;
    original_watermark_image_url: string;
  }[];
  amenities: {
    id: number;
    name: string;
    code: string;
    type: string;
  }[];
  tenantApplication: string;
  propertyManagers: {
    id: number;
    system_id: number;
    role: string;
    is_primary: boolean;
    name: string;
    work_phone: string;
    email: string;
    company: string;
  }[];
  websiteUrls: string;
  watermarkSettings: {
    id: number;
    system_id: number;
    is_watermark_image_applied: boolean;
    is_watermark_text_applied: boolean;
    watermark_image_transparency: number;
    watermark_image_scale: number;
    watermark_image_document_id: number | null;
    watermarked_image_document_id: number | null;
    watermark_text: string;
    watermark_text_style: string;
    watermark_text_size: number;
    is_watermark_text_bold: boolean;
    is_watermark_text_italic: boolean;
    is_watermark_text_underlined: boolean;
    watermark_text_color: string;
    watermark_text_transparency: number;
    watermark_text_alignment_left: boolean;
    watermark_text_alignment_center: boolean;
    watermark_text_alignment_right: boolean;
    watermark_text_alignment_top: boolean;
    watermark_text_alignment_middle: boolean;
    watermark_text_alignment_bottom: boolean;
    watermark_text_alignment_vertical: boolean;
    watermarked_text_document_id: number | null;
  };
  signedUrl: string;
  DetailURL: string;
  PreviousTargetRent: string;
  portfolio: {
    portfolio_name: string;
    portfolio_abbreviation: string;
  };
}
